#!/usr/bin/env python3
"""Regenerate deterministic Q15 SSB FIR and NCO tables (Python stdlib only)."""
import argparse
import math
import subprocess
from pathlib import Path

RATE = 24000
TAPS = 257

def generate():
    real, imag = [], []
    for n in range(TAPS):
        k = n - (TAPS - 1) / 2
        lowpass = 2 * 1200 / RATE if k == 0 else math.sin(2 * math.pi * 1200 * k / RATE) / (math.pi * k)
        window = 0.42 - 0.5 * math.cos(2 * math.pi * n / (TAPS - 1)) + 0.08 * math.cos(4 * math.pi * n / (TAPS - 1))
        # Complex bandpass, centered at +1500 Hz. Unity complex gain.
        real.append(round(32768 * lowpass * window * math.cos(2 * math.pi * 1500 * k / RATE)))
        imag.append(round(32768 * lowpass * window * math.sin(2 * math.pi * 1500 * k / RATE)))
    sine = [round(32767 * math.sin(2 * math.pi * n / 1024)) for n in range(1024)]
    out = '// Generated by scripts/generate_dsp.py; do not hand edit.\n'
    for name, values in [('FIR_RE', real), ('FIR_IM', imag), ('SINE', sine)]:
        out += f'pub const {name}: [i16; {len(values)}] = [\n'
        for pos in range(0, len(values), 16):
            out += '    ' + ', '.join(map(str, values[pos:pos+16])) + ',\n'
        out += '];\n'
    return out

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    path = root / 'firmware/src/dsp_tables.rs'
    formatted = subprocess.run(['rustfmt', '--edition', '2024'], input=generate(),
                               text=True, capture_output=True, check=True, cwd=root).stdout
    if args.check:
        if path.read_text() != formatted:
            raise SystemExit('DSP tables differ; run scripts/generate_dsp.py')
        print('DSP tables match generator')
    else:
        path.write_text(formatted)
